//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCompany
    {
        public TblCompany()
        {
            this.TblGenaralReceipts = new HashSet<TblGenaralReceipt>();
            this.TblInvoiceHeads = new HashSet<TblInvoiceHead>();
            this.TblProformaInvoiceHeads = new HashSet<TblProformaInvoiceHead>();
            this.TblReceipts = new HashSet<TblReceipt>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TblGenaralReceipt> TblGenaralReceipts { get; set; }
        public virtual ICollection<TblInvoiceHead> TblInvoiceHeads { get; set; }
        public virtual ICollection<TblProformaInvoiceHead> TblProformaInvoiceHeads { get; set; }
        public virtual ICollection<TblReceipt> TblReceipts { get; set; }
    }
}
