//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInvoiceBodyTemp
    {
        public int Id { get; set; }
        public int BodyRowId { get; set; }
        public int Fk_InvoiceNarrttionId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int FK_CustomerId { get; set; }
        public int FK_JobMasterId { get; set; }
        public string Create_By { get; set; }
        public string Narration { get; set; }
    }
}
