//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblJobMasterAssignTemp
    {
        public int Id { get; set; }
        public int RowId { get; set; }
        public bool IsProjectOnwer { get; set; }
        public string TypeOftable { get; set; }
        public int TypeOftableId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> BudgetedHours { get; set; }
        public string Designation { get; set; }
        public string Create_By { get; set; }
    }
}
