//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Customer
    {
        public int Id { get; set; }
        public int Fk_CustomerGroupId { get; set; }
        public string VatType { get; set; }
        public string Address { get; set; }
        public string TaxNo { get; set; }
        public string VatNo { get; set; }
        public string SVatNo { get; set; }
        public string Fax { get; set; }
        public string TelOne { get; set; }
        public string TelSecond { get; set; }
        public int Fk_GradeMasterId { get; set; }
        public string Email { get; set; }
        public string ContactPersonOne { get; set; }
        public string ContactPersonSecond { get; set; }
        public int Fk_PartnerId { get; set; }
        public int Fk_ManagerId { get; set; }
        public int Fk_LegalStatusMasterId { get; set; }
        public int Fk_SectorMasterId { get; set; }
        public int Fk_IntroductionId { get; set; }
        public int Fk_InternationslReferalId { get; set; }
        public Nullable<System.DateTime> DateOfJoined { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string Create_By { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Edit_By { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public string WorkGroupCode { get; set; }
        public string GradeMasterCode { get; set; }
        public string Partner { get; set; }
        public string ManagerName { get; set; }
        public string LegalStatusMasterCode { get; set; }
        public string SectorMasterCode { get; set; }
        public string IntroductionCode { get; set; }
        public string InternationslReferalCode { get; set; }
    }
}
