//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EmployeeWiseJObCositingDetails
    {
        public int PartnerTableId { get; set; }
        public int Fk_JobMasterId { get; set; }
        public int Fk_CustomerId { get; set; }
        public string TypeOfTable { get; set; }
        public int TypeOfTableId { get; set; }
        public bool PartnersIsDelete { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public int JobmasterId { get; set; }
        public string JobCode { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> PreViewvalue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsReActivate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> ReActivateDate { get; set; }
        public bool IsActive { get; set; }
        public bool JobmasterIsDelete { get; set; }
        public string CombinedName { get; set; }
        public string CombinedCode { get; set; }
        public Nullable<decimal> BudgetedHours { get; set; }
        public Nullable<decimal> ActualHours { get; set; }
        public decimal LocationRate { get; set; }
        public Nullable<decimal> EmployeeRateValue { get; set; }
        public decimal HoursVarianceValue { get; set; }
        public decimal VarianceValue { get; set; }
    }
}
