//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Employee
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string Nic { get; set; }
        public string Email { get; set; }
        public bool IsManager { get; set; }
        public bool IsPartner { get; set; }
        public int Fk_TitleId { get; set; }
        public int Fk_DesginationId { get; set; }
        public int Fk_DepartmentId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string Create_By { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Edit_By { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public string JObPrefixCode { get; set; }
        public System.DateTime DateOfJoin { get; set; }
        public string DepartmentCode { get; set; }
        public string DesignationCode { get; set; }
        public string titleCode { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
    }
}
