//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EmployeeVisitingRates
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string EmployeeName { get; set; }
        public int Fk_EmployeeId { get; set; }
        public bool IsApplyTravelingCost { get; set; }
        public int Fk_LocationId { get; set; }
        public bool IsDelete { get; set; }
        public string LocationName { get; set; }
        public decimal Rate { get; set; }
    }
}
