//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GetJObActualValue
    {
        public int Fk_JobMasterId { get; set; }
        public int Fk_CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public string JobCode { get; set; }
        public string VatType { get; set; }
        public Nullable<decimal> PreViewvalue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public bool JobmasterIsDelete { get; set; }
        public Nullable<decimal> ActualHours { get; set; }
        public Nullable<decimal> TotalBudgetedHours { get; set; }
        public Nullable<decimal> ActualValue { get; set; }
        public Nullable<decimal> BudgetValue { get; set; }
        public int VarianceValue { get; set; }
        public string FullDetails { get; set; }
    }
}
