//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GeneralReceipts
    {
        public int Id { get; set; }
        public string ReceiptNo { get; set; }
        public System.DateTime Date { get; set; }
        public int Fk_WorkGroupId { get; set; }
        public int Fk_CustomerId { get; set; }
        public int Fk_AccountId { get; set; }
        public string Narration { get; set; }
        public int Fk_CompanyId { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public string PaymentType { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public bool IsDelete { get; set; }
        public bool IsPrint { get; set; }
        public string Create_By { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Edit_By { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public string CustomerName { get; set; }
        public string WorkGroupName { get; set; }
        public string CompanyName { get; set; }
        public string AccountName { get; set; }
    }
}
