//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LaberUtilizationSummaryWorkTypeAndGroup
    {
        public Nullable<int> TransactionId { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<int> Fk_JobMasterId { get; set; }
        public Nullable<int> Fk_EmployeeId { get; set; }
        public string Narration { get; set; }
        public string JobCode { get; set; }
        public Nullable<bool> IsApplyTravelingCost { get; set; }
        public Nullable<int> Fk_LocationId { get; set; }
        public Nullable<decimal> WorkingHours { get; set; }
        public Nullable<int> Fk_WorkTypeId { get; set; }
        public Nullable<int> Fk_CustomerId { get; set; }
        public string Groups { get; set; }
        public string Worktypes { get; set; }
        public string EmployeeName { get; set; }
    }
}
