//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ProformaInvoiceHead
    {
        public int Id { get; set; }
        public string InvoiceNoProforma { get; set; }
        public int Fk_DepartmentIdOne { get; set; }
        public int Fk_DepartmentIdTwo { get; set; }
        public int Fk_DepartmentIdThird { get; set; }
        public string DocNo { get; set; }
        public System.DateTime Date { get; set; }
        public string OurReferance { get; set; }
        public string YourReferance { get; set; }
        public int Fk_WorkGroupId { get; set; }
        public int Fk_CustomerId { get; set; }
        public int Fk_PartnerOne { get; set; }
        public int Fk_PartnerSecond { get; set; }
        public int Fk_PartnerThird { get; set; }
        public int Fk_ManagerOne { get; set; }
        public int Fk_ManagerSecond { get; set; }
        public int Fk_ManagerThird { get; set; }
        public string TaxType { get; set; }
        public int Fk_NatureId { get; set; }
        public string NoNVat { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> ValueNBT { get; set; }
        public Nullable<decimal> ValueVAT { get; set; }
        public Nullable<decimal> TotalReceivedAmount { get; set; }
        public Nullable<decimal> NoNVatPrecentage { get; set; }
        public Nullable<decimal> VatPercentage { get; set; }
        public Nullable<decimal> NBTPercentage { get; set; }
        public string NarrationOne { get; set; }
        public string NarrationTwo { get; set; }
        public int Fk_InvoiceShortNarrationId { get; set; }
        public int Fk_JobMasterId { get; set; }
        public Nullable<decimal> LastYearAmount { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> IsActiveDate { get; set; }
        public bool IsDelete { get; set; }
        public string Create_By { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Edit_By { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public int Fk_CompanyId { get; set; }
        public bool IsPartnerOneComfirm { get; set; }
        public Nullable<System.DateTime> PartnerOneComfirmDate { get; set; }
        public string CompanyName { get; set; }
        public string JobCode { get; set; }
        public string DepartmentOneName { get; set; }
        public string DepartmentTwoName { get; set; }
        public string DepartmentThreeName { get; set; }
        public string WorkGroupName { get; set; }
        public string CustomerName { get; set; }
        public string PartnerOneName { get; set; }
        public string PartnerTwoName { get; set; }
        public string PartnerThreeName { get; set; }
        public string ManagerOneName { get; set; }
        public string ManagerTwoName { get; set; }
        public string ManagerThreeName { get; set; }
    }
}
