//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOPHRMSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_WIPReportMonthly
    {
        public string Month { get; set; }
        public int MonthNumber { get; set; }
        public int Fk_JobMasterId { get; set; }
        public int Fk_EmployeeId { get; set; }
        public string Narration { get; set; }
        public decimal TotalHours { get; set; }
        public decimal EmployeeRateValue { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public string JobCode { get; set; }
        public string JobNarration { get; set; }
        public Nullable<int> Fk_CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string EmployeeName { get; set; }
        public string DesignationName { get; set; }
    }
}
